### ISSUE TITLE
Add global contexts

### ISSUE THREAD

**Issue by brijeshprasad89** [snowplow-incubator/snowplow-react-native-tracker#104]
We have this method `addGlobalContexts` in standard snowplow library. However I don't see any such method in React native equivalent. How can we add global contexts?

**Comment by colmsnowplow** [comment]
Hi @brijeshprasad89, currently that method hasn't been bridged over to react-native yet, so adding contexts can only be done manually rather than globally.

If I remember correctly, we discussed it at the time but decided it was out of scope as a piece of work to refactor the native trackers was still pending. 

I'll check in on progress with that and flag your interest with the product team - I can't say when we plan the next piece of significant work on this project, but for sure global contexts are something we're keen to add.

Thanks for raising. :)
