### ISSUE TITLE
Allow offline tracking

### ISSUE THREAD

**Issue by jeroenver** [snowplow-incubator/snowplow-react-native-tracker#30]
Thanks for the good work on the tracker, we use it in the app for our newspapers. 
This app allows people to read content offline since it pre-loads some content so people can read it on the train for example.
It would be great if we could also track this offline behaviour. For the moment this tracking gets lost since there is no implementation for the emitter callback handler.
I would be able to add this for android but xcode is totally unknown to me.

Thanks!

**Comment by colmsnowplow** [comment]
Hi @jeroenver, neither the iOS nor the Android tracker require an emitter callback to be manually instrumented in order to handle offline events. 

For both trackers, the out-of-the-box behaviour is that any events that fail to send will be stored in a queue, which will be flushed on the next attempt to send an event. 

Closing this ticket as it seems to be down to just that - but if you have any evidence that the tracker isn't sending offline events as expected, please let us know, we can re-open or attempt to explain.
