### ISSUE TITLE
Add trackPageView

### ISSUE THREAD

**Issue by max-tgam** [snowplow-incubator/snowplow-react-native-tracker#33]
Please add page view tracking in React Native apps to make it easier to match same type of encounters across web and app.

@colmsnowplow I can do a PR for this. Please let me know if there is anything in particular that jumps out at you that I should be aware of

**Comment by colmsnowplow** [comment]
Hi @max-tgam! Thanks for opening the issue.

I have no objection to page views being added, but my only comment is that I didn't think they'd be useful in a mobile environment, since screen views are already available, and you won't have anything related to web (or page view id).

If it is something you want to add, happy for you to go for it though - I've added comments on going about making the changes in my comment on [the other issue](https://github.com/snowplow-incubator/snowplow-react-native-tracker/issues/34#issuecomment-604014304).

**Comment by max-tgam** [comment]
@colmsnowplow Sounds good. We prefer tom use page_views for certain interactions that are similar in app and web. For page view id we are using custom context anyway so it is not a problem. This will technically make this closer to other App Trackers, I can also include my notes on how I added this so that anyone can add other events as need.

**Comment by max-tgam** [comment]
@colmsnowplow I have created PR for this here https://github.com/snowplow-incubator/snowplow-react-native-tracker/pull/43

Please let me know how should I update documentation. Also for modifications I made - if you want me to share the notes on how I modified it - please let let me know how to share those.
