### ISSUE TITLE
Allow to set log level for debugging

### ISSUE THREAD

**Issue by fasci** [snowplow-incubator/snowplow-react-native-tracker#99]
**Is your feature request related to a problem? Please describe.**
Currently the tracker is like a black box, and as a developer I cannot clearly see what is sent to the endpoint, without having to use a package analyzer and then prettify the request. I can therefore not easily verify that I send the correct tracking data without/before talking to BI.

**Describe the solution you'd like**
I'd like to be able to set a log level. The JS console in Chrome should then print everything that is sent. Even better: The Snowplow Debugger Chrome extension works with React Native.

**Comment by colmsnowplow** [comment]
Hi @fasci,

[Snowplow Mini](https://github.com/snowplow/snowplow-mini) and [Snowplow Micro](https://github.com/snowplow-incubator/snowplow-micro) serve exactly this purpose - across all of the trackers these are the best way to test tracking. They offer you a way to test that events pass validations and enrichments succeed, which the browser or chrome extension can't.

Micro is great for CI/CD, Mini is great for dev-testing. Both should be straightforward to set up.

The Chrome debugger is a third party tool that uses browser network requests to access the information it presents, so that wouldn't be a viable option.

As for the idea of logging to console, it's certainly something that would be good to do, but I'm not sure how straightforward it would be - logging is done within the native context so they would appear within the actual Obj-c/Java logs. 

We'd be open to hearing suggestions/outlines of how this would be instrumented, and considering it for a future release if it seems feasibly straightforward.

**Comment by fasci** [comment]
Hi @colmsnowplow,

Thanks for the quick reply and the links to Snowplow Mini and Micro. While on the first look, it seems to be a bit complex to install and setup a docker image for this purpose, I might give it a try. For me as a frontend developer, it would be great to have a simple macOS app that sets up a local server under the hood, I could then point my endpoint to localhost, and have a look at what's being tracked. 

Regarding the logging, it would already be great to have the native logLevel properties (of the newer versions of the native tracking libraries) exposed to the React Native tracker, even if the logs will only show up in Xcode and Logcat.

But I will close this request, as you provided a way to achieve what I want.

**Comment by colmsnowplow** [comment]
If you have docker, it should be relatively straightforward to spin up an instance of Micro locally. It can also be spun up manually without docker but that would mean you'd need to worry about configuring the routes yourself, which can be quite the hassle. 

Re-opening as it's something I'd like to explore in the future. Thanks for raising. :)

**Comment by adatzer** [comment]
This is resolved as part of #128 . (cc @fasci )
More specifically, by upgrading iOS and Android trackers to v2, the `logLevel` is now a property of the trackerConfig and so can be configured when initializing the tracker: [Documentation](https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/react-native-tracker/introduction/#trackerconfiguration).
Closing.
